name: task_manager_test
description: Production-ready Task Manager application built with Clean Architecture.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.1

  # Networking
  dio: ^5.8.0+1

  # Dependency injection
  get_it: ^8.0.3

  # Serialization
  json_annotation: ^4.9.0

  # Local storage
  shared_preferences: ^2.5.3
  # Device info
  device_info_plus: ^13.1.0
  # Flutter launcher icons
  flutter_launcher_icons: ^0.14.4
  # Flutter native splash
  flutter_native_splash: ^2.4.7
  # Flutter screenutil
  flutter_screenutil: ^5.9.3
  # Pretty dio logger
  # Pretty dio logger
  pretty_dio_logger: ^1.4.0
  # Flutter secure storage
  flutter_secure_storage: ^10.3.1
  # Pretty dio logger
  # Retrofit
  retrofit: ^4.9.2
  # Freezed
  freezed_annotation: ^3.1.0
  freezed: ^3.2.5
  fluttertoast: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  retrofit_generator: ^10.2.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_background: "#8d278f" # You can use a color or image for the background
  adaptive_icon_foreground: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: Inter
    fonts:
    - asset: assets/fonts/Inter-Bold.ttf
      weight: 700
    - asset: assets/fonts/Inter-Medium.ttf
      weight: 500
    - asset: assets/fonts/Inter-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Inter-Regular.ttf
      weight: 400
